[project]
name = "mcpenum"
version = "0.1.5"
description = "MCP server enumeration tool"
dynamic = [
    "dependencies",
]
requires-python = ">=3.11"

dependencies = [
    "asyncio",
    "fastmcp",
]
