[project]
name = "mcpenum"
version = "0.1.8"
description = "MCP server enumeration tool"
requires-python = ">=3.11"

dependencies = [
    "asyncio",
    "fastmcp",
]

[project.scripts]
mcpenum = "mcpenum:main"
