[project]
name = "mcpenum"
version = "0.1.7"
description = "MCP server enumeration tool"
requires-python = ">=3.11"

[project.scripts]
mcpenum = "mcpenum:main"

dependencies = [
    "asyncio",
    "fastmcp",
]
